<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books [
  <!ELEMENT books (book)+>
  <!ELEMENT book (author*)>
  <!ATTLIST book
    title CDATA #REQUIRED
    content CDATA #IMPLIED 
    location (local|foreign) "local"
    type CDATA #FIXED "paper"
    press CDATA #REQUIRED
    price CDATA #REQUIRED
  >
  <!ELEMENT author (#PCDATA)>
]>
<books>
  <book title="자바프로그래밍" content="자바 기초 문법에 대한 책이다" type="paper" press="비트출판사" price="32000"></book>
  <book title="자바프로그래밍2" location="foreign" press="비트출판사" price="42000">
    <author>홍길동</author>
    <author>임꺽정</author>
  </book>
</books>
