<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books [
  <!ELEMENT books (book)>
  <!ELEMENT book (title,content,press,price)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT content (#PCDATA)>
  <!ELEMENT press (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
]>
<books>
  <book>
    <title>자바 프로그래밍</title>
    <content>자바 기초 문법에 대한 책이다</content>
    <press>비트출판사</press>
    <price>32000</price>
  </book>
  
</books>
